### ISSUE TITLE
Big mistake at MaxTipAge made in last commit

### ISSUE THREAD

**Issue by Himan2001** [LINCPlatform/LINC#1]
> nMaxTipAge = 60 * 60 * 60;

This is big mistake: 6 * 60 * 60 is per default even to high. (=for BTC blocktime 10 Minutes!)

When the coin uses a blocktime of 300 seconds, that must be reduced to 3 or better 1,5
and NOT rised x10 ;-)

By the way... BTC Timing is used on other Routines, too.

**Comment by LINCPlatform** [comment]
Yes, it's high but temporarily because of the not succeeded fork we have last block more than 6h already. It should be raised now because the chain is stuck. When the chain move forward it will be definitely lowered in the next update. For blocktime 2 minutes it may be 1h or even 30m.

**Comment by Himan2001** [comment]
we use actualy 1.5 * 60 * 60 for a coin with 240 minutes blocktime, this is linear to the 10 minutes of BTC. but this MaxTipAge with the same formula is at another place again in the fork! don´t have info actualy by hand, where it is. But in another part of the code again 10 minutes blocktime is expected. When you made a change here to correct to real blocktime, you need to correct the other function, too.
